language: node_js
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- 10.6.0
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem update --system
install:
- cd log4js
- npm ci
before_script:
- npm ci
script:
- grunt --gruntfile "Gruntfile.js" build
deploy:
  provider: releases
  api_key:
    secure: iKdorqXgiTH3RcLLNj8Q4AoRWxpYA6yT7YDYKnuORz3tcAvHrIBmt+ff6h5zsn2JVGkFamc0njfYdrOfLdc4+cQQfQVq80OhJJnkIQ0WgOtG0yt+yVHKb8lWBGr9P0lMvvBuROsuxGl9jPcgkUTtuvxHoJ3T24WlLDGXJSWdCzw=
  file: log4js/target/*.zip
  skip_cleanup: true
  on:
    repo: stritti/log4js
    branch: master	
