language: node_js
node_js:
  - "4.2.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8  
      
before_install:
  - cd log4js
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem update --system
install:
  - npm install
  - npm install -g bower grunt-cli

before_script:
  - cd log4js
  - npm install
script:
  - grunt --gruntfile "Gruntfile.js" build --verbose

